#!/bin/sh
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --mem-per-cpu=16G # Maximum memory required per CPU (in megabytes)
#SBATCH --mem-per-cpu=MaxMemPerCPU # maybe this?
#SBATCH --time=168:00:00 # run time in hh:mm:ss
#SBATCH --job-name=microenvironment.HCC
#SBATCH --error=/work/serussolab/samworthy/microenvironment.HCC.%J.err
#SBATCH --output=/work/serussolab/samworthy/microenvironment.HCC.%J.out

module load R
Rscript microenvironment.HCC.R
