#!/bin/sh
#SBATCH --nodes=1
#SBATCH --mem=60000 # 60gb
#SBATCH --time=168:00:00 # run time in hh:mm:ss
#SBATCH --job-name=microenvironment.HCC
#SBATCH --error=/work/serussolab/samworthy/microenvironment.HCC.%J.err
#SBATCH --output=/work/serussolab/samworthy/microenvironment.HCC.%J.out

# With conda environments, it is best practice to purge currently loaded modules
# to prevent any version or environment conflicts

module purge
module load anaconda

conda activate /work/serussolab/samworthy/myconda2

Rscript HCC.test.R
