#!/bin/sh
#SBATCH --nodes=1
#SBATCH --mem=180000 # 180gb
#SBATCH --time=168:00:00 # run time in hh:mm:ss
#SBATCH --job-name=centroid.range
#SBATCH --error=/work/serussolab/samworthy/centroid.range.%J.err
#SBATCH --output=/work/serussolab/samworthy/centroid.range.%J.out

module purge
module load anaconda

conda activate myconda2

Rscript 19.Centroid.Distance.Mapping.R
