#!/bin/sh
#SBATCH --nodes=1
#SBATCH --mem=180000 # 180gb
#SBATCH --time=168:00:00 # run time in hh:mm:ss
#SBATCH --job-name=clim.MRM
#SBATCH --error=/work/serussolab/samworthy/range.size.%J.err
#SBATCH --output=/work/serussolab/samworthy/range.size.%J.out

# With conda environments, it is best practice to purge currently loaded modules
# to prevent any version or environment conflicts

module purge
module load anaconda

conda activate /work/serussolab/samworthy/myconda2

Rscript Q1.MRM.R
