#!/bin/sh
#SBATCH --nodes=1
#SBATCH --mem=300000 # 180gb
#SBATCH --time=168:00:00 # run time in hh:mm:ss
#SBATCH --job-name=microclim.MRM
#SBATCH --error=/work/serussolab/samworthy/microclim.MRM.%J.err
#SBATCH --output=/work/serussolab/samworthy/microclim.MRM.%J.out

# With conda environments, it is best practice to purge currently loaded modules
# to prevent any version or environment conflicts

module purge
module load anaconda

conda activate /work/serussolab/samworthy/myconda2

Rscript 6.Microclim.MRM.R
