#!/bin/sh
#SBATCH --nodes=1
#SBATCH --mem=180000 # 180gb
#SBATCH --time=168:00:00 # run time in hh:mm:ss
#SBATCH --job-name=biological.soil.null
#SBATCH --error=/work/serussolab/samworthy/biological.soil.null.%J.err
#SBATCH --output=/work/serussolab/samworthy/biological.soil.null.%J.out

module purge
module load anaconda

conda activate /work/serussolab/samworthy/myconda2

Rscript 13.Soil.Biological.Null.R
